databases:
  # PostgreSQL Database
  - name: healapp-db
    databaseName: healapp
    user: healapp_user
    plan: free

services:
  # Backend API Service
  - type: web
    name: healapp-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PGHOST
        fromDatabase:
          name: healapp-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: healapp-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: healapp-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: healapp-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: healapp-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: "org.postgresql.Driver"
      - key: JWT_SECRET
        generateValue: true
      - key: APP_AVATAR_STORAGE_LOCATION
        value: /app/uploads/avatar
      - key: APP_BLOG_STORAGE_LOCATION
        value: /app/uploads/blog
      - key: APP_CONFIG_STORAGE_LOCATION
        value: /app/uploads/config
      - key: APP_AVATAR_URL_PATTERN
        value: https://healapp-backend.onrender.com/uploads/avatar/
      - key: APP_BLOG_URL_PATTERN
        value: https://healapp-backend.onrender.com/uploads/blog/
      - key: APP_CONFIG_URL_PATTERN
        value: https://healapp-backend.onrender.com/uploads/config/
      # Email Configuration - Add real values in Render Dashboard
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: ""
      - key: SMTP_PASSWORD
        value: ""      # Twilio Configuration - Add real values in Render Dashboard
      - key: TWILIO_ACCOUNT_SID
        value: ""
      - key: TWILIO_AUTH_TOKEN
        value: ""
      - key: TWILIO_PHONE_NUMBER
        value: ""
      - key: TWILIO_VERIFIED_NUMBERS
        value: "+84349079940,+84982677408"
      # Stripe Configuration - Add real values in Render Dashboard
      - key: STRIPE_API_KEY
        value: ""
      - key: STRIPE_PUBLISHABLE_KEY
        value: ""
      # MCP/Gemini AI Configuration - Add real values in Render Dashboard
      - key: MCP_API_KEY
        value: ""
      - key: MCP_API_PROVIDER
        value: "google"
      - key: MCP_API_BASE_URL
        value: "https://generativelanguage.googleapis.com/v1beta"
      - key: MCP_API_MODEL
        value: "gemini-2.0-flash"
      # Banking Configuration
      - key: BANKING_MB_API_URL
        value: "https://api.mbbank.com.vn"
      - key: BANKING_MB_API_KEY
        value: ""
      - key: BANKING_MB_DEVICE_ID
        value: "healapp-device-001"
      - key: BANKING_MB_ACCOUNT_NUMBER
        value: "0349079940"
      - key: BANKING_MB_ACCOUNT_NAME
        value: "NGUYEN VAN CUONG"
      # SMS Configuration
      - key: SMS_ENABLED
        value: "true"
      - key: SMS_PROVIDER
        value: "twilio"
      - key: SMS_DEVELOPMENT_MODE
        value: "false"
      # QR Payment Configuration
      - key: QR_PAYMENT_EXPIRY_HOURS
        value: "24"
      - key: QR_PAYMENT_CHECK_INTERVAL_MINUTES
        value: "2"
      - key: QR_PAYMENT_AUTO_CHECK_ENABLED
        value: "true"
      # Banking Integration Configuration
      - key: BANKING_API_TIMEOUT_SECONDS
        value: "30"
      - key: BANKING_API_RETRY_ATTEMPTS
        value: "3"
      - key: BANKING_SIMULATION_ENABLED
        value: "false"
      # Content Moderation Configuration
      - key: HEALAPP_MODERATION_ENABLED
        value: "true"
      - key: HEALAPP_MODERATION_CACHE_ENABLED
        value: "true"
      - key: HEALAPP_MODERATION_CACHE_TTL
        value: "3600"      # AI Assistant Configuration
      - key: HEALAPP_ASSISTANT_MAX_HISTORY
        value: "10"
      # JWT Configuration
      - key: JWT_ACCESS_TOKEN_EXPIRATION
        value: "3600000"
      - key: JWT_REFRESH_TOKEN_EXPIRATION
        value: "86400000"
      - key: JWT_ISSUER
        value: "HealApp"
  # Frontend Service
  - type: web
    name: healapp-frontend
    runtime: node
    plan: free
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://healapp-backend.onrender.com
      - key: NODE_ENV
        value: production