spring.application.name=HealApp

#database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HealApp;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

#file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#avatar
app.avatar.storage.location=src/main/resources/static/img/avatar
app.avatar.url.pattern=/img/avatar/

#blog images
app.blog.storage.location=src/main/resources/static/img/blog
app.blog.url.pattern=/img/blog/

#app config images (logo, banner)
app.config.storage.location=src/main/resources/static/img/app
app.config.url.pattern=/img/app/


# Java mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alicek23004@gmail.com
spring.mail.password=sjsc imoc typf hhdz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#logging
logging.level.com.healapp.service.EmailService=DEBUG

# Consultation fee
app.consultation.hourly-rate=150000.0

#Stripe
stripe.api.key=sk_test_51QmtJb1JnNChU1O6uTsQH4DdEVPeq5N0DDObL0coVEI3uHPMcMjE8FKUsKkiZRdURFKuWK3Seb3cV09jb806kXgL00gkKPoIkv
stripe.publishable.key=pk_test_51QmtJb1JnNChU1O6d5yXhY2eAf1Qejxk0H4JmIhBEZ5ZydPSjUEJSZZBfXgx3WKIPZ9PeIOUgVfvR55ZcIVnEOVp00b450JglU

# MCP Server Configuration
mcp.api.provider=google
mcp.api.base-url=https://generativelanguage.googleapis.com/v1beta
mcp.api.key=AIzaSyCU5h9fEpnpui6hahhL0fsb90EpM7YKRpQ
mcp.api.model=gemini-2.0-flash

# Content Moderation Configuration
healapp.moderation.enabled=true
healapp.moderation.cache.enabled=true
healapp.moderation.cache.ttl=3600

# AI Assistant Configuration
healapp.assistant.max-history=10